// The game's files as Apple shipped them: what must be present, and intact, before the game
// runs. The table itself is generated by tools/manifest.py from a known-good copy.
#pragma once

#include <cstddef>
#include <cstdint>

namespace holdem::gamedata {

struct ManifestEntry {
    const char* path;  // relative to the game directory, '/'-separated
    uint32_t size;
    uint32_t crc32;
};

extern const ManifestEntry GAME_MANIFEST[];
extern const size_t GAME_MANIFEST_SIZE;

// The game directory's name on the iPod, and the image inside it. `33333` is what the folder is
// called on the device; keeping the name means a copy taken off an iPod installs as it is.
constexpr const char* GAME_DIRECTORY_NAME = "33333";
constexpr const char* GAME_IMAGE_PATH = "Executables/HoldEm_1_1_2563291.bin";

}  // namespace holdem::gamedata
