#!/usr/bin/env python3
"""Write src/gamedata/manifest_data.cpp: the name, size and CRC-32 of every file of the game.

    tools/manifest.py "<path to>/Games_RO/33333"

The game's directory as Apple shipped it is the reference. What is left out is everything that
is *written into* that directory rather than shipped in it — Finder droppings, the game's own
saves, and this program's settings and key bindings — so a folder the game has been played in
still produces the right table, and a folder the game later writes into still verifies against
it. Texas Hold'em keeps its save in `<language>.lproj/data.txt` at the folder's root — `en.lproj/
data.txt`, created empty on the first boot (PLAN.md, progress log 2026-08-27) — which is a
different folder from the shipped `Data/en.lproj/` and `Localization/en.lproj/`, so the rule is
"a `.lproj` folder directly under the root", not the name `.lproj` anywhere. The `.sav` patterns
are the other titles' save names, kept because a shipped folder never contains one and a file
with that name can only have been written.
"""

import re
import sys
import zlib
from pathlib import Path

IGNORED_NAMES = {".DS_Store", "settings.txt", "bindings.txt"}
# `.sav`, and `.sav0`/`.sav1`/… — the other titles' save names; Lost numbers its slots.
IGNORED_SUFFIX_PATTERN = re.compile(r"\.sav[0-9]*$")
# `en.lproj/data.txt` and its siblings for the other ten languages: this game's save file.
SAVE_FOLDER_PATTERN = re.compile(r"^[a-z]{2}\.lproj$")
OUTPUT = Path(__file__).resolve().parent.parent / "src" / "gamedata" / "manifest_data.cpp"


def is_save_file(path: Path, root: Path) -> bool:
    relative = path.relative_to(root)
    return len(relative.parts) == 2 and SAVE_FOLDER_PATTERN.match(relative.parts[0]) is not None


def wanted(path: Path, root: Path) -> bool:
    return (
        path.is_file()
        and path.name not in IGNORED_NAMES
        and IGNORED_SUFFIX_PATTERN.search(path.name) is None
        and not is_save_file(path, root)
    )


def main(argv):
    if len(argv) != 2:
        sys.exit(__doc__)
    root = Path(argv[1])
    files = sorted(p for p in root.rglob("*") if wanted(p, root))
    lines = [
        "// Generated by tools/manifest.py — do not edit. The game's files as shipped: relative",
        "// path, size in bytes, CRC-32 of the contents (gamedata/manifest.h).",
        '#include "gamedata/manifest.h"',
        "",
        "namespace holdem::gamedata {",
        "",
        "const ManifestEntry GAME_MANIFEST[] = {",
    ]
    for path in files:
        data = path.read_bytes()
        relative = path.relative_to(root).as_posix()
        lines.append(f'    {{"{relative}", {len(data)}, 0x{zlib.crc32(data):08x}u}},')
    lines += [
        "};",
        "",
        f"const size_t GAME_MANIFEST_SIZE = {len(files)};",
        "",
        "}  // namespace holdem::gamedata",
        "",
    ]
    OUTPUT.write_text("\n".join(lines))
    print(
        f"{len(files)} files -> {OUTPUT.relative_to(Path.cwd()) if OUTPUT.is_relative_to(Path.cwd()) else OUTPUT}"
    )


if __name__ == "__main__":
    main(sys.argv)
