#!/usr/bin/env python3
"""Write src/gamedata/manifest_data.cpp: the name, size and CRC-32 of every file of the game.

    tools/manifest.py "<path to>/Games_RO/1500C"

The game's directory as Apple shipped it is the reference. What is left out is everything that
is *written into* that directory rather than shipped in it — Finder droppings, the game's own
save, and this program's settings and key bindings — so a folder the game has been played in
still produces the right table, and a folder the game later writes into still verifies against
it. The Sims Bowling keeps its save in `savefile.dat` at the folder's root: created empty during
the boot, written later (PLAN.md difference 6). The reference folder this repository was
developed against holds one from an earlier emulator session, which is exactly why the rule is
needed. The `.sav` patterns are the other titles' save names, kept because a shipped folder never
contains one and a file with that name can only have been written.
"""

import re
import sys
import zlib
from pathlib import Path

IGNORED_NAMES = {".DS_Store", "settings.txt", "bindings.txt", "savefile.dat"}
# `.sav`, and `.sav0`/`.sav1`/… — the other titles' save names; Lost numbers its slots.
IGNORED_SUFFIX_PATTERN = re.compile(r"\.sav[0-9]*$")
OUTPUT = Path(__file__).resolve().parent.parent / "src" / "gamedata" / "manifest_data.cpp"


def wanted(path: Path) -> bool:
    return (
        path.is_file()
        and path.name not in IGNORED_NAMES
        and IGNORED_SUFFIX_PATTERN.search(path.name) is None
    )


def main(argv):
    if len(argv) != 2:
        sys.exit(__doc__)
    root = Path(argv[1])
    files = sorted(p for p in root.rglob("*") if wanted(p))
    lines = [
        "// Generated by tools/manifest.py — do not edit. The game's files as shipped: relative",
        "// path, size in bytes, CRC-32 of the contents (gamedata/manifest.h).",
        '#include "gamedata/manifest.h"',
        "",
        "namespace bowling::gamedata {",
        "",
        "const ManifestEntry GAME_MANIFEST[] = {",
    ]
    for path in files:
        data = path.read_bytes()
        relative = path.relative_to(root).as_posix()
        lines.append(f'    {{"{relative}", {len(data)}, 0x{zlib.crc32(data):08x}u}},')
    lines += [
        "};",
        "",
        f"const size_t GAME_MANIFEST_SIZE = {len(files)};",
        "",
        "}  // namespace bowling::gamedata",
        "",
    ]
    OUTPUT.write_text("\n".join(lines))
    print(
        f"{len(files)} files -> {OUTPUT.relative_to(Path.cwd()) if OUTPUT.is_relative_to(Path.cwd()) else OUTPUT}"
    )


if __name__ == "__main__":
    main(sys.argv)
