// The game's files as Apple shipped them: what must be present, and intact, before the game
// runs. The table itself is generated by tools/manifest.py from a known-good copy.
#pragma once

#include <cstddef>
#include <cstdint>

namespace minigolf::gamedata {

struct ManifestEntry {
    const char* path;  // relative to the game directory, '/'-separated
    uint32_t size;
    uint32_t crc32;
};

extern const ManifestEntry GAME_MANIFEST[];
extern const size_t GAME_MANIFEST_SIZE;

// The game directory's name on the iPod, and the image inside it.
constexpr const char* GAME_DIRECTORY_NAME = "88888";
constexpr const char* GAME_IMAGE_PATH = "Executables/Minigolf_1_1_2563296.bin";

}  // namespace minigolf::gamedata
