#!/usr/bin/env python3
"""Write src/gamedata/manifest_data.cpp: the name, size and CRC-32 of every file of the game.

    tools/manifest.py "<path to>/Games_RO/88888"

The game's directory as Apple shipped it is the reference. Finder droppings (`.DS_Store`) and
the save files the game itself writes (`*.sav`) are not part of it and are left out, so a
directory the game has been played in still verifies.
"""
import sys
import zlib
from pathlib import Path

IGNORED_NAMES = {".DS_Store"}
IGNORED_SUFFIXES = {".sav"}
OUTPUT = Path(__file__).resolve().parent.parent / "src" / "gamedata" / "manifest_data.cpp"


def wanted(path: Path) -> bool:
    return path.is_file() and path.name not in IGNORED_NAMES and path.suffix not in IGNORED_SUFFIXES


def main(argv):
    if len(argv) != 2:
        sys.exit(__doc__)
    root = Path(argv[1])
    files = sorted(p for p in root.rglob("*") if wanted(p))
    lines = [
        "// Generated by tools/manifest.py — do not edit. The game's files as shipped: relative",
        "// path, size in bytes, CRC-32 of the contents (gamedata/manifest.h).",
        '#include "gamedata/manifest.h"',
        "",
        "namespace minigolf::gamedata {",
        "",
        "const ManifestEntry GAME_MANIFEST[] = {",
    ]
    for path in files:
        data = path.read_bytes()
        relative = path.relative_to(root).as_posix()
        lines.append(f'    {{"{relative}", {len(data)}, 0x{zlib.crc32(data):08x}u}},')
    lines += [
        "};",
        "",
        f"const size_t GAME_MANIFEST_SIZE = {len(files)};",
        "",
        "}  // namespace minigolf::gamedata",
        "",
    ]
    OUTPUT.write_text("\n".join(lines))
    print(f"{len(files)} files -> {OUTPUT.relative_to(Path.cwd()) if OUTPUT.is_relative_to(Path.cwd()) else OUTPUT}")


if __name__ == "__main__":
    main(sys.argv)
